### ISSUE TITLE
_uuid_all upgrade step not applied

### ISSUE THREAD

**Issue by micmord** [RedTurtle/collective.tablepage#17]
Starting from an old version (in my case v0.4 with setup profile 1100) the "_uuid_all(portal)" function on setuphandlers.py is not applied.
So, from  version 0.9 and newest, the old datas do not work anymore:
AttributeError: 'PersistentMapping' object has no attribute 'UID'

Manually workaround:
Install the last version 0.10.1 (setup profile 1340) and go to
ZMI -> "portal_setup/manage_upgrades" and select "collective.tablepage:default" upgrades.
Show old upgrades and check "Upgrade to 0.8" or "Upgrade to 0.8b1" according to current setuphandlers.py.
Then apply the last one (0.8.1).

**Comment by keul** [comment]
Plone upgrade must be done through Plone UI, not reinstalling from ZMI `portal_quickinstaller`
