### ISSUE TITLE
selection field validator does not work with umlaut characters (äö)

### ISSUE THREAD

**Issue by petri** [RedTurtle/collective.tablepage#21]
Adding a selection field and a set of choices with alternatives fails the validator. Choosing a value with umlauts results in error:

'The field "myfield" does not fit any of the vocabulary values'

**Comment by petri** [comment]
The problem is in ```validate``` method of ```ValidatorEnforceVocabulary```.

Here, ```vocabulary``` items are unicode, whereas ```data``` is a string, apparently UTF-8 encoded. Python cannot convert it to unicode automatically so comparison always fails.

    def validate(self, configuration, data=None):
        col_id = configuration['id']
        self.field.configuration = configuration
        vocabulary = self.field.vocabulary()
        data = data or self.field.request.form.get(col_id)
        if data and data not in vocabulary:
            return _('error_enforce_vocabulary',
                     default='The field "$name" does not fit any of the vocabulary values',
                     mapping={'name': configuration.get('label', col_id).decode('utf-8')})

Perhaps just change:

        if data and data not in vocabulary:

to

        if data and data.decode("utf-8") not in vocabulary:

???

**Comment by keul** [comment]
Thanks, you probably get the point! Unluckily I've no time now for testing it. Could you find some time to provide a pull request?
