### ISSUE TITLE
Match import & export columns

### ISSUE THREAD

**Issue by petri** [RedTurtle/collective.tablepage#26]
Currently, when exporting, the column labels are used, whereas when importing, the column id's are. This makes roundtripping hard, or copying over data from other table with same columns.

**Comment by keul** [comment]
You must export from the "edit table" if you plan to use that CSV for importing again.
Importing from the view is intended to be for final users (no UID but URL, and so on)

**Comment by keul** [comment]
PS: I can't close the issue, or review all of your recent ones, because I'm not working for RedTurtle anymore and unluckily I lost my powers on that repo.
I don't know if this addon is still maintained, I think you must ping RedTurtle by email.

**Comment by petri** [comment]
Thanks @keul . All the best for you at your new job!

**Comment by keul** [comment]
@petri thanks!
